#!/bin/sh

test ! -f /srv/spigot/spigot.jar && mv /srv/spigot-default/spigot.jar /srv/spigot/
test ! -f /srv/spigot/eula.txt && mv /srv/spigot-default/eula.txt /srv/spigot/

cd /srv/spigot/

exec java -Xmx$MEMLIMIT -jar spigot.jar --nojline
