#!/bin/sh -x

test ! -f /srv/spigot/spigot.jar && cp /srv/spigot-default/spigot.jar /srv/spigot/
test ! -f /srv/spigot/eula.txt && cp /srv/spigot-default/eula.txt /srv/spigot/

cd /srv/spigot/

exec java -Xmx$MEMLIMIT -jar spigot.jar --nojline
